### ISSUE TITLE
Library fails suddenly

### ISSUE THREAD

**Issue by MrMegamind** [FreeTubeApp/yt-channel-info#133]
Hi
I recently started to get this error:

TypeError: Cannot read properties of undefined (reading 'alerts')
    at Function.getChannelStats (E:\node\ytc_usa\node_modules\yt-channel-info\app\youtube-grabber.js:494:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
E:\node\ytc_usa\node_modules\yt-channel-info\app\youtube-grabber.js:494
    if (typeof (channelPageDataResponse.alerts) !== 'undefined') {
                                        ^

TypeError: Cannot read properties of undefined (reading 'alerts')
    at Function.getChannelStats (E:\node\ytc_usa\node_modules\yt-channel-info\app\youtube-grabber.js:494:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Can anyone help please

**Comment by usback** [comment]
i have same issue 


what is alers ???


/media/data/worker/juju-video-scraper/node_modules/yt-channel-info/app/helper.js:62
    if (typeof (channelPageDataResponse.alerts) !== 'undefined') {
                                        ^

TypeError: Cannot read properties of undefined (reading 'alerts')
    at YoutubeGrabberHelper.parseChannelVideoResponse (/media/data/worker/video/node_modules/yt-channel-info/app/helper.js:62:41)
    at Function.getChannelVideosNewest (/media/data/worker/video/node_modules/yt-channel-info/app/fetchers/channel.js:7:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.getChannelVideos (/media/data/worker/video/node_modules/yt-channel-info/app/youtube-grabber.js:223:14)

**Comment by absidue** [comment]
Please check that you haven't upgraded axios to 1.2.0. As you can see in https://github.com/FreeTubeApp/yt-channel-info/pull/131 axios had breaking changes.
