### ISSUE TITLE
getChannelVideos causes error

### ISSUE THREAD

**Issue by hazycora** [FreeTubeApp/yt-channel-info#15]
Here's some code I wrote to test it.
```javascript
const ytch = require('yt-channel-info')

ytch.getChannelVideos("UCIOqgcoAGI2fycb89gPXMPA", 'popular').then((channelvideos) => {
    var j = JSON.stringify({
        "data": {"videos": channelvideos},
        "source": "youtube"
    });
    console.log(j);
}).catch((err) => {
    console.log(err)
})
```
This should grab the channel videos from [https://www.youtube.com/channel/UCIOqgcoAGI2fycb89gPXMPA](https://www.youtube.com/channel/UCIOqgcoAGI2fycb89gPXMPA). Instead, it causes the following error.
```
TypeError: Cannot read property 'title' of undefined
    at Function.parseVideo (C:\Users\hazycora\Documents\GitHub\testing\node_modules\yt-channel-info\app\helper.js:80:23)
    at C:\Users\hazycora\Documents\GitHub\testing\node_modules\yt-channel-info\app\helper.js:55:19
    at Array.map (<anonymous>)
    at Function.parseChannelVideoResponse (C:\Users\hazycora\Documents\GitHub\testing\node_modules\yt-channel-info\app\helper.js:54:49)
    at Function.getChannelVideosPopular (C:\Users\hazycora\Documents\GitHub\testing\node_modules\yt-channel-info\app\fetchers\channel.js:57:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.getChannelVideos (C:\Users\hazycora\Documents\GitHub\testing\node_modules\yt-channel-info\app\youtube-grabber.js:128:16)
```

**Comment by PrestonN** [comment]
I'm aware of the current issue. A fix will be coming out sometime this weekend. I've already got a WIP for it.

**Comment by PrestonN** [comment]
This should be fixed now. Let me know if you ever see any more issues.
