### ISSUE TITLE
Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by hazycora** [FreeTubeApp/yt-channel-info#23]
I've got this error when trying to use getChannelInfo and getChannelVideos with some channels.
```
TypeError: Cannot read property 'title' of undefined
    at C:\Users\hazycora\Documents\GitHub\testing\node_modules\yt-channel-info\app\youtube-grabber.js:55:28
    at Array.map (<anonymous>)
    at Function.getChannelInfo (C:\Users\hazycora\Documents\GitHub\testing\node_modules\yt-channel-info\app\youtube-grabber.js:51:61)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
From looking at youtube-grabber.js, I think YouTube's changed how continuation works, at least for some channels. I experimented with trying to fix it myself, but it seems my fix only moved the problem somewhere else.
It doesn't happen with all channels, but [Ben Awad's](https://www.youtube.com/channel/UC-8QAzbLcRglXeN_MY9blyw) causes it consistently.

**Comment by Michal-Szczepaniak** [comment]
I'm not sure if it should be new issue so i will post it there as it might be related. 
`ytch.getChannelInfo(channelId)` returns empty array `{}` for some channels for example `UC1DCedRgGHBdm81E1llLhOQ`

**Comment by hazycora** [comment]
My issue has been fixed in a recent update.
