### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'alerts')

### ISSUE THREAD

**Issue by mbg206** [FreeTubeApp/yt-channel-info#70]
Everytime I call getChannelVideos (`let res = await ytch.getChannelVideos({channelId: channelId});` where channelId is `'UCBy0RRHpgTyA7Vx0o5HpfLg'`) the following is thrown:

```
/home/runner/myApp/node_modules/yt-channel-info/app/helper.js:58
    if (typeof (response.data.response.alerts) !== 'undefined') {
                                       ^

TypeError: Cannot read properties of undefined (reading 'alerts')
    at YoutubeGrabberHelper.parseChannelVideoResponse (/home/runner/myApp/node_modules/yt-channel-info/app/helper.js:58:40)
    at Function.getChannelVideosNewest (/home/runner/myApp/node_modules/yt-channel-info/app/fetchers/channel.js:11:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.getChannelVideos (/home/runner/myApp/node_modules/yt-channel-info/app/youtube-grabber.js:212:14)
    at async getChannelVideos (/home/runner/myApp/src/youtube.js:9:15)
```

It seems that this is an issue with yt-channel-info, not my code (i think)

**Comment by ChunkyProgrammer** [comment]
I'll post a fix later today
